name: 🚀 Feature Request
description: feature request for OceanBase
title: "[feat.]: <title>"
labels: ["type: feature"]
assignees: []
body:
  - type: checkboxes
    attributes:
      label: Please check the issue list for the same feature first
      options:
        - label: I have searched the existing issues.
          required: true
        - label: Please try full text in English and attach precise description.
          required: true
  - type: textarea
    attributes:
      label: Use Case
      description: A clear and concise description of what is the intended usage scenario is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you've considered
    validations:
      required: false
  - type: textarea
    attributes:
      label: Other information
      description: Any other information about the feature.
    validations:
      required: false
